#!/bin/sh
if [ -f ${OPENSHIFT_DATA_DIR}/.schema_deployed ]; then 
  /opt/rh/php54/root/usr/bin/php $OPENSHIFT_REPO_DIR/php/update.php --feeds --quiet &> $OPENSHIFT_PHP_LOG_DIR/rss_update.log 
fi
exit 0

